server:
  port: 8080
  servlet:
    context-path: /obbm

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/OBBM_3"
    username: root
    password: system
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 10 # in second
  refreshable-duration: 1209600 # in seconds

outbound:
  identity:
    client-id: "102785858700-jbqau42hb0m77erfgafhqitm980cgcr0.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: "http://localhost:3000/authenticate"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

payos:
  client-id: "f0ec7a97-606b-4881-bb8e-b31e28ce14bd"
  api-key: "523dc500-76f4-4ef1-97a3-d759a9bf05da"
  checksum-key: "58077fc2d772211aaf3c7bb5f765e98207a4cc4518a9972fc2ea454dff8d95ae"
  base-url: "https://sandbox.payos.com"
  success-url: "http://localhost:8080/obbm/payment/success"
  cancel-url: "http://localhost:8080/obbm/payment/cancel"

cloudinary:
  cloud-name: "dpu6e4ebx"
  api-key: "461762216833814"
  api-secret: "pxMYhsccAckpcGS8nr0HaWP2Ry0"

payment:
  vnPay:
    url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    tmnCode: "8DRA46XX"
    secretKey: "0BO3U3B3CILA5KM4JJ531B63A5NW9J2X"
    returnUrl: "http://localhost:8080/obbm/payment/vn-pay-callback"
    version: 2.1.0
    command: "pay"
    orderType: "other"




