server:
  port: 8080
  servlet:
    context-path: /obbm

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/OBBM"
    username: root
    password: system
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 1800 # in second
  refreshable-duration: 2592000 # in seconds

#spring:
#  security:
#    enabled=false:

openapi:
  service:
    api-docs: api-service
    server: http://localhost:8080
    title: API Service
    version: 1.0.0