server:
  port: 8080
  servlet:
    context-path: /obbm

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/OBBM_2"
    username: root
    password: system
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 1800 # in second
  refreshable-duration: 1209600 # in seconds

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs